/* Deleta estrutura para testes */
/*drop database controleambientesdb;*/

/* Comando cria banco de dados */
create Database controleambientesdb;

/* Comando cria tabela de usuários */
create table controleambientesdb.users(
	c_EmailUsers char(255) not null unique,
    c_NameUsers char(255) not null,
    c_LogginUsers char(255) not null,
    c_PasswUsers char(255) not null,
    d_DataUsers datetime not null,
    primary key (c_EmailUsers)
);

/* Comando cria tabela de registro eventos */
create table controleambientesdb.dataevent(
	n_IdEvent int not null auto_increment,
    d_DataEvent datetime not null,
    c_ObjectEvent char(10) not null,
    c_Event char(20) not null,
    n_WattsEvent SMALLINT,
    primary key (n_IdEvent)
);

/* Comando cria tabela de configuração */
create table controleambientesdb.config(
	n_IdUnicoConfig int not null,
    d_DataConfig datetime not null,
    c_IpArduinoConfig char(255) not null,
    n_ComboTypeA0Config TINYINT not null,
    n_ComboTypeA1Config TINYINT not null,
    n_ComboTypeA2Config TINYINT not null,
    n_ComboTypeA3Config TINYINT not null,
    n_ComboTypeA4Config TINYINT not null,
    n_ComboTypeA5Config TINYINT not null,
    n_ComboTypeA6Config TINYINT not null,
    n_ComboTypeA7Config TINYINT not null,
    n_ComboTypeA8Config TINYINT not null,
    n_ComboTypeA9Config TINYINT not null,
    n_ComboTypeA10Config TINYINT not null,
    n_ComboTypeA11Config TINYINT not null,
    n_ComboTypeA12Config TINYINT not null,
    n_ComboTypeA13Config TINYINT not null,
    n_ComboTypeA14Config TINYINT not null,
    n_ComboTypeA15Config TINYINT not null,
    n_ComboType2Config TINYINT not null,
    n_ComboType3Config TINYINT not null,
    n_ComboType4Config TINYINT not null,
    n_ComboType5Config TINYINT not null,
    n_ComboType6Config TINYINT not null,
    n_ComboType7Config TINYINT not null,
    n_ComboType8Config TINYINT not null,
    n_ComboType9Config TINYINT not null,
    n_ComboType22Config TINYINT not null,
    n_ComboType23Config TINYINT not null,
    n_ComboType24Config TINYINT not null,
    n_ComboType25Config TINYINT not null,
    n_ComboType26Config TINYINT not null,
    n_ComboType27Config TINYINT not null,
    n_ComboType28Config TINYINT not null,
    n_ComboType29Config TINYINT not null,
    n_ComboType30Config TINYINT not null,
    n_ComboType31Config TINYINT not null,
    n_ComboType32Config TINYINT not null,
    n_ComboType33Config TINYINT not null,
    n_ComboType34Config TINYINT not null,
    n_ComboType35Config TINYINT not null,
    n_ComboType36Config TINYINT not null,
    n_ComboType37Config TINYINT not null,
    n_ComboType38Config TINYINT not null,
    n_ComboType39Config TINYINT not null,
    n_ComboType40Config TINYINT not null,
    n_ComboType41Config TINYINT not null,
    n_ComboType42Config TINYINT not null,
    n_ComboType43Config TINYINT not null,
    n_ComboType44Config TINYINT not null,
    n_ComboType45Config TINYINT not null,
    n_ComboType46Config TINYINT not null,
    n_ComboType47Config TINYINT not null,
    n_ComboType48Config TINYINT not null,
    n_ComboType49Config TINYINT not null,
    n_ComboType50Config TINYINT not null,
    n_ComboType51Config TINYINT not null,
    n_comboColA0Config TINYINT not null,
    n_comboColA1Config TINYINT not null,
	n_comboColA2Config TINYINT not null,
    n_comboColA3Config TINYINT not null,
    n_comboColA4Config TINYINT not null,
    n_comboColA5Config TINYINT not null,
    n_comboColA6Config TINYINT not null,
    n_comboColA7Config TINYINT not null,
    n_comboColA8Config TINYINT not null,
    n_comboColA9Config TINYINT not null,
    n_comboColA10Config TINYINT not null,
    n_comboColA11Config TINYINT not null,
    n_comboColA12Config TINYINT not null,
    n_comboColA13Config TINYINT not null,
    n_comboColA14Config TINYINT not null,
    n_comboColA15Config TINYINT not null,
    n_comboCol2Config TINYINT not null,
    n_comboCol3Config TINYINT not null,
    n_comboCol4Config TINYINT not null,
    n_comboCol5Config TINYINT not null,
    n_comboCol6Config TINYINT not null,
    n_comboCol7Config TINYINT not null,
    n_comboCol8Config TINYINT not null,
    n_comboCol9Config TINYINT not null,
    n_comboCol22Config TINYINT not null,
    n_comboCol23Config TINYINT not null,
    n_comboCol24Config TINYINT not null,
    n_comboCol25Config TINYINT not null,
    n_comboCol26Config TINYINT not null,
    n_comboCol27Config TINYINT not null,
    n_comboCol28Config TINYINT not null,
    n_comboCol29Config TINYINT not null,
    n_comboCol30Config TINYINT not null,
    n_comboCol31Config TINYINT not null,
    n_comboCol32Config TINYINT not null,
    n_comboCol33Config TINYINT not null,
    n_comboCol34Config TINYINT not null,
    n_comboCol35Config TINYINT not null,
    n_comboCol36Config TINYINT not null,
    n_comboCol37Config TINYINT not null,
    n_comboCol38Config TINYINT not null,
    n_comboCol39Config TINYINT not null,
    n_comboCol40Config TINYINT not null,
    n_comboCol41Config TINYINT not null,
    n_comboCol42Config TINYINT not null,
    n_comboCol43Config TINYINT not null,
    n_comboCol44Config TINYINT not null,
    n_comboCol45Config TINYINT not null,
    n_comboCol46Config TINYINT not null,
    n_comboCol47Config TINYINT not null,
    n_comboCol48Config TINYINT not null,
    n_comboCol49Config TINYINT not null,
    n_comboCol50Config TINYINT not null,
    n_comboCol51Config TINYINT not null,
    n_comboRowA0Config TINYINT not null,
    n_comboRowA1Config TINYINT not null,
    n_comboRowA2Config TINYINT not null,
    n_comboRowA3Config TINYINT not null,
    n_comboRowA4Config TINYINT not null,
    n_comboRowA5Config TINYINT not null,
    n_comboRowA6Config TINYINT not null,
    n_comboRowA7Config TINYINT not null,
    n_comboRowA8Config TINYINT not null,
    n_comboRowA9Config TINYINT not null,
    n_comboRowA10Config TINYINT not null,
    n_comboRowA11Config TINYINT not null,
    n_comboRowA12Config TINYINT not null,
    n_comboRowA13Config TINYINT not null,
    n_comboRowA14Config TINYINT not null,
    n_comboRowA15Config TINYINT not null,
    n_comboRow2Config TINYINT not null,
    n_comboRow3Config TINYINT not null,
    n_comboRow4Config TINYINT not null,
    n_comboRow5Config TINYINT not null,
    n_comboRow6Config TINYINT not null,
    n_comboRow7Config TINYINT not null,
    n_comboRow8Config TINYINT not null,
    n_comboRow9Config TINYINT not null,
    n_comboRow22Config TINYINT not null,
    n_comboRow23Config TINYINT not null,
    n_comboRow24Config TINYINT not null,
    n_comboRow25Config TINYINT not null,
    n_comboRow26Config TINYINT not null,
    n_comboRow27Config TINYINT not null,
    n_comboRow28Config TINYINT not null,
    n_comboRow29Config TINYINT not null,
    n_comboRow30Config TINYINT not null,
    n_comboRow31Config TINYINT not null,
    n_comboRow32Config TINYINT not null,
    n_comboRow33Config TINYINT not null,
    n_comboRow34Config TINYINT not null,
    n_comboRow35Config TINYINT not null,
    n_comboRow36Config TINYINT not null,
    n_comboRow37Config TINYINT not null,
    n_comboRow38Config TINYINT not null,
    n_comboRow39Config TINYINT not null,
    n_comboRow40Config TINYINT not null,
    n_comboRow41Config TINYINT not null,
    n_comboRow42Config TINYINT not null,
    n_comboRow43Config TINYINT not null,
    n_comboRow44Config TINYINT not null,
    n_comboRow45Config TINYINT not null,
    n_comboRow46Config TINYINT not null,
    n_comboRow47Config TINYINT not null,
    n_comboRow48Config TINYINT not null,
    n_comboRow49Config TINYINT not null,
    n_comboRow50Config TINYINT not null,
    n_comboRow51Config TINYINT not null,
    n_txtWats_A0Config SMALLINT,
    n_txtWats_A1Config SMALLINT,
    n_txtWats_A2Config SMALLINT,
    n_txtWats_A3Config SMALLINT,
    n_txtWats_A4Config SMALLINT,
    n_txtWats_A5Config SMALLINT,
    n_txtWats_A6Config SMALLINT,
    n_txtWats_A7Config SMALLINT,
    n_txtWats_A8Config SMALLINT,
    n_txtWats_A9Config SMALLINT,
    n_txtWats_A10Config SMALLINT,
    n_txtWats_A11Config SMALLINT,
    n_txtWats_A12Config SMALLINT,
    n_txtWats_A13Config SMALLINT,
    n_txtWats_A14Config SMALLINT,
    n_txtWats_A15Config SMALLINT,
    n_txtWats_2Config SMALLINT,
    n_txtWats_3Config SMALLINT,
    n_txtWats_4Config SMALLINT,
    n_txtWats_5Config SMALLINT,
    n_txtWats_6Config SMALLINT,
    n_txtWats_7Config SMALLINT,
    n_txtWats_8Config SMALLINT,
    n_txtWats_9Config SMALLINT,
    n_txtWats_22Config SMALLINT,
    n_txtWats_23Config SMALLINT,
    n_txtWats_24Config SMALLINT,
    n_txtWats_25Config SMALLINT,
    n_txtWats_26Config SMALLINT,
    n_txtWats_27Config SMALLINT,
    n_txtWats_28Config SMALLINT,
    n_txtWats_29Config SMALLINT,
    n_txtWats_30Config SMALLINT,
    n_txtWats_31Config SMALLINT,
    n_txtWats_32Config SMALLINT,
    n_txtWats_33Config SMALLINT,
    n_txtWats_34Config SMALLINT,
    n_txtWats_35Config SMALLINT,
    n_txtWats_36Config SMALLINT,
    n_txtWats_37Config SMALLINT,
    n_txtWats_38Config SMALLINT,
    n_txtWats_39Config SMALLINT,
    n_txtWats_40Config SMALLINT,
    n_txtWats_41Config SMALLINT,
    n_txtWats_42Config SMALLINT,
    n_txtWats_43Config SMALLINT,
    n_txtWats_44Config SMALLINT,
    n_txtWats_45Config SMALLINT,
    n_txtWats_46Config SMALLINT,
    n_txtWats_47Config SMALLINT,
    n_txtWats_48Config SMALLINT,
    n_txtWats_49Config SMALLINT,
    n_txtWats_50Config SMALLINT,
    n_txtWats_51Config SMALLINT,
    primary key (n_IdUnicoConfig)
);

/* Inseri usuário padrão na aplicação */
insert Into controleambientesdb.users(c_EmailUsers, c_NameUsers, c_LogginUsers, c_PasswUsers, d_DataUsers) Values ('adm@adm.com.br', 'adm', 'adm', md5('adm'), now());  


